spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${LB_AUTH_ISSUER_URI:http://127.0.0.1:9001}
      client:
        registration:
          maintenance-client:
            provider: spring
            client-id: maintenance-client
            client-secret: 12345
            authorization-grant-type: authorization_code
            redirect-uri: ${LB_MAINTENANCE_URI:http://127.0.0.1:9090}/api/users/authorized
            scope:
              - openid
              - profile
              - read
              - write
            client-name: maintenance-client
        provider:
          spring:
            issuer-uri: ${LB_AUTH_ISSUER_URI:http://127.0.0.1:9001}
# Configuration by default
config:
  texto: Configurando ambiente por defecto
---
spring:
  config:
    activate:
      on-profile: dev
config:
  texto: Configurando ambiente de desarrollo
---
spring:
  config:
    activate:
      on-profile: prod
config:
  texto: Configurando ambiente de produccion